### PR TITLE
Integration tests

### PR DESCRIPTION
**Pull request by dmarcelino**
* Adds Integration tests to anchor to ensure that changes in anchor don't break waterline core.
* Adds badges to README.md

cc: @devinivy, @particlebanana, @tjwebb

### CODE REVIEW

**Comment by devinivy** [comment]
Is this a standard pattern for integration tests?  `npm linking`, `wget`ing, etc.  I genuinely just don't know!  Should an `npm unlink` happen at the end?  Or somehow just restore the state of whether the package was originally linked or not.

**Comment by dmarcelino** [comment]
I'm not sure there are "standard" patterns for integration tests, given how different they can be... :) This tries to mimic what a developer would do to test anchor. Regarding `npm unlink`, tough question... In Travis it doesn't matter as it always cleans the environment before a build. In a developer's machine is trickier... If hadn't linked beforehand then we should unlink. Otherwise we should keep the link. In other words we should leave the environment as it was. Not sure if there is a way to check the link...

**Comment by dmarcelino** [comment]
@devinivy, an alternative to using `npm link` is to use a symbolic link which is slightly cleaner (doesn't change the developer's environment). I've written it below, do you prefer this option to my original proposal?

``` shell
ROOT=$(shell pwd)

	
test-integration:
	@echo Running integration tests...
	mkdir test_integration
	cd test_integration; \
		wget https://github.com/balderdashy/waterline/archive/master.zip; \
		unzip -q master.zip
	cd test_integration/waterline-master; \
		npm install; \
		rm -rf node_modules/anchor; \
		ln -s $(ROOT) node_modules/anchor; \
		npm test
	rm -rf test_integration

```

**Comment by devinivy** [comment]
Yes, this is nice :)

**Comment by dmarcelino** [comment]
Done: 870dd98!
I've also done the same to balderdashy/waterline-schema#21.

**Pull request merged**
