### PR TITLE
Adds GeoJSON validation

### PR DESCRIPTION
**Pull request by secrettriangle**

### CODE REVIEW

**Comment by tjwebb** [comment]
@secrettriangle I'm sorry that we let this sit here for so long. Are you still interested in having this merged?

**Comment by secrettriangle** [comment]
Yes please! :sunglasses:

**Comment by tjwebb** [comment]
Can you merge the latest into your PR?

**Comment by secrettriangle** [comment]
Done!

**Comment by tjwebb** [comment]
Awesome, thanks

**Comment by tjwebb** [comment]
@secrettriangle how are you using geojson in waterline? everything working ok?

**Comment by heckj** [comment]
@tjwebb @dbkaplun We recently updated to a more recent version of anchor through Waterline, and found that gjtk, which is merged with this, is a GPL framework, which makes it unacceptable for us to use within our commercial product.

Is there a non GPL library that can do this same thing, or a way to make this dependency more 'optional', so that it's not automatically installed and adding in the viral licensing?

**Comment by particlebanana** [comment]
@heckj whoa good catch. We need to get that out of there asap.

**Comment by dbkaplun** [comment]
FYI I've filed an issue upstream dmtucker/gjtk-js#24 requesting a more lax license -- hopefully that will be changed so we won't have to remove the validator!

**Comment by particlebanana** [comment]
@dbkaplun @tjwebb is looking into getting a replacement lib in.

**Comment by particlebanana** [comment]
Fixed in https://github.com/balderdashy/anchor/pull/87

**Pull request merged**
